# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e58ac3bd6ee4fde9683ddb19624e9a8c90aa130dd34b1915ed26a02f1d049c6f6394b74ddbbcc4f5874a5cb65dd8e3b0beeb048153ed42958b81219a6f7da28f

test:
  secret_key_base: 596e6343031f58345c67e3f3fec0ff41be32867c39850a62265643e0ff0bcb79e79e1ab0945283164816ad375c19a9568f39cd9d23a94881732c557d0464f4a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
